name: Sync Runner

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    if: github.repository == 'gebangfeng/docker-images-sync'
    steps:
      - name: Set up runner
        run: |
          wget https://github.com/OpenCIDN/OpenCIDN/releases/download/v0.0.23/runner_linux_amd64 -O /usr/local/bin/runner && chmod +x /usr/local/bin/runner
      - name: Sync Runner
        run: |
          /usr/local/bin/runner ${{ secrets.NEW_STORAGE_ARGS }}
